export type {
  CellMargins,
  ConditionalFormatStyle,
  EmphasisMark,
  FloatingTableProperties,
  LineSpacingRule,
  ParagraphAlignment,
  ParagraphFormatting,
  SpacingExplicit,
  TabLeader,
  TableBorders,
  TableCellFormatting,
  TableFormatting,
  TableGridChange,
  TableLook,
  TableMeasurement,
  TableRowFormatting,
  TableWidthType,
  TabStop,
  TabStopAlignment,
  TextDirection,
  TextEffect,
  TextFormatting,
  UnderlineStyle,
} from "@stll/docx-core/model";
