export { applyFolioAIEditOperations, type FolioAIEditView } from "./apply";
export {
  clampRangeToDocSize,
  resolveFolioAIBlockRange,
  resolveFolioAITextRange,
  type DocPositionRange,
} from "./blockRange";
export { buildAnnotatedBlockText } from "./clean-text";
export {
  getCommentAnchorsFromDoc,
  getTrackedChangesFromDoc,
  type FolioCommentAnchor,
  type FolioReviewChange,
  type FolioReviewChangeKind,
} from "./read";
export {
  createFolioAIEditSnapshot,
  createFolioAITextRangeHandle,
  hashFolioAIBlockText,
  normalizeFolioAIBlockText,
} from "./snapshot";
export { getFolioDocumentOutline, readFolioDocumentSection } from "./scoped-reading";
export { getFolioParaIdFromBlockId } from "../types/block-id";
export { diffWordSegments } from "./word-diff";
export {
  FOLIO_REVIEWED_VIEWS,
  FolioDocumentStoryNotFoundError,
  UnsupportedFolioReviewedViewError,
  isFolioReviewedView,
  type FolioApplyDocumentOperationsToStoryOptions,
  type FolioDocumentStory,
  type FolioDocumentStoryHandle,
  type FolioEditableDocumentStoryHandle,
  type FolioReadReviewedStoryOptions,
  type FolioReviewedStory,
  type FolioReviewedView,
} from "./headless";
export type { WordDiffSegment } from "./word-diff";
export type {
  FolioAIBlock,
  FolioAIBlockAnchor,
  FolioAIBlockKind,
  FolioAIBlockPreviewRun,
  FolioAIComment,
  FolioAIEditAppliedOperation,
  FolioAIEditApplyMode,
  FolioAIEditApplyResult,
  FolioAIEditOperation,
  FolioAIEditPrecondition,
  FolioAIEditReviewMeta,
  FolioAIEditSeverity,
  FolioAIEditSkipReason,
  FolioAIEditSkippedOperation,
  FolioAIEditSnapshot,
  FolioAIInlineFormatting,
  FolioAISignatureParty,
  FolioAITextRangeHandle,
  FolioDocumentNavigationTarget,
  FolioDocumentOutline,
  FolioDocumentOutlineEntry,
  FolioDocumentSection,
  FolioDocumentSectionHandle,
  FolioDocumentSectionReadResult,
} from "./types";
export {
  applyFolioDocumentOperations,
  assertSupportedFolioDocumentOperationVersion,
  FOLIO_DOCUMENT_OPERATION_CONTRACT_VERSION,
  FOLIO_DOCUMENT_OPERATION_BATCH_MODES,
  FOLIO_DOCUMENT_OPERATION_MODES,
  FOLIO_DOCUMENT_OPERATION_MODES_BY_TYPE,
  FOLIO_DOCUMENT_OPERATION_PRECONDITIONS,
  FOLIO_DOCUMENT_OPERATION_STORIES,
  FOLIO_DOCUMENT_OPERATION_TYPES,
  getFolioDocumentOperationCapabilities,
  getFolioDocumentOperationIssues,
  getFolioDocumentOperationReceipts,
  InvalidFolioDocumentOperationBatchError,
  isSupportedFolioDocumentOperationVersion,
  isFolioDocumentOperationModeSupported,
  parseFolioDocumentOperationBatch,
  UnsupportedFolioDocumentOperationVersionError,
  type ApplyFolioDocumentOperationsOptions,
  type FolioDocumentOperation,
  type FolioDocumentOperationAffectedTarget,
  type FolioDocumentOperationBatch,
  type FolioDocumentOperationCapabilities,
  type FolioDocumentOperationMode,
  type FolioDocumentOperationIssue,
  type FolioDocumentOperationPrecondition,
  type FolioDocumentOperationRecovery,
  type FolioDocumentOperationReceipt,
  type FolioDocumentOperationType,
  type FolioDocumentOperationResult,
  type FolioDocumentOperationStatus,
  type FolioDocumentOperationStory,
  type FolioDocumentOperationUndoFailureReason,
  type FolioDocumentOperationUndoHandle,
  type FolioDocumentOperationUndoResult,
} from "../document-operations";
