/**
 * Generate the all-locales catalog and independent locale entries from JSON.
 * Raw JSON stays outside the source-mirrored build graph. Generated TypeScript
 * modules retain named and default bindings for downstream bundlers.
 *
 * Usage: bun scripts/i18n-catalogs-gen.ts [--check]
 * CI checks every generated core catalog and adapter re-export for drift.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { FOLIO_LOCALES } from "../packages/core/src/i18n/messages/locales";

const messagesDir = path.resolve(import.meta.dir, "../packages/core/src/i18n/messages");
const outputPath = path.join(messagesDir, "catalogs.gen.ts");
const checkOnly = process.argv.includes("--check");
const normalizeLineEndings = (value: string) => value.replaceAll("\r\n", "\n");

const entries = FOLIO_LOCALES.map((locale) => {
  const json = readFileSync(path.join(messagesDir, `${locale}.json`), "utf8");
  const value = JSON.stringify(JSON.parse(json), null, 2);
  // Re-indent the JSON body so the object literal reads cleanly inside CATALOGS.
  const indented = value
    .split("\n")
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join("\n");
  return `  ${JSON.stringify(locale)}: ${indented}`;
}).join(",\n");

const banner = `// Auto-generated by scripts/i18n-catalogs-gen.ts from the sibling *.json locale
// catalogs. Do not edit manually; run \`bun run i18n:sync\` to regenerate.
//
// The locale catalogs are inlined here (rather than imported as raw \`.json\`) so
// tsdown's \`unbundle: true\` build keeps \`.json\` out of the build graph and emits
// no malformed per-locale \`dist/i18n/messages/<locale>.js\` modules. The \`*.json\`
// files remain the source of truth the i18n tooling reads.`;

const contents = `${banner}\nexport const CATALOGS = {\n${entries},\n} as const;\n`;

const outputs = new Map([[outputPath, contents]]);
for (const locale of FOLIO_LOCALES) {
  const catalog = JSON.stringify(
    JSON.parse(readFileSync(path.join(messagesDir, `${locale}.json`), "utf8")),
    null,
    2,
  );
  outputs.set(
    path.join(messagesDir, `${locale}.gen.ts`),
    `// Auto-generated by scripts/i18n-catalogs-gen.ts. Do not edit manually.
import type { FolioMessages } from "../messages";

// Keep the public declaration identical to getFolioMessages without copying every key.
export const messages: FolioMessages = ${catalog};
export default messages;
`,
  );
}
for (const adapter of ["react", "vue"]) {
  const adapterDir = path.resolve(import.meta.dir, `../packages/${adapter}/src/i18n/messages`);
  for (const locale of FOLIO_LOCALES) {
    outputs.set(
      path.join(adapterDir, `${locale}.ts`),
      `// Auto-generated by scripts/i18n-catalogs-gen.ts. Do not edit manually.
export { default, messages } from "@stll/folio-core/i18n/messages/${locale}";
`,
    );
  }
  outputs.set(
    path.join(adapterDir, "locales.ts"),
    `// Auto-generated by scripts/i18n-catalogs-gen.ts. Do not edit manually.
export { FOLIO_LOCALES, type FolioLocale } from "@stll/folio-core/i18n/messages/locales";
`,
  );
}

let drifted = false;
for (const [output, generated] of outputs) {
  if (checkOnly) {
    const existing = existsSync(output) ? readFileSync(output, "utf8") : "";
    if (normalizeLineEndings(existing) === normalizeLineEndings(generated)) continue;
    console.error(
      `Error: ${path.relative(process.cwd(), output)} is out of sync. Run \`bun run i18n:sync\`.`,
    );
    drifted = true;
    continue;
  }
  mkdirSync(path.dirname(output), { recursive: true });
  writeFileSync(output, generated);
}
if (drifted) process.exit(1);
console.log(`${checkOnly ? "Checked" : "Wrote"} ${outputs.size} generated message modules`);
