#!/usr/bin/env bun
/**
 * Generates a TypeScript declaration file for the English locale that preserves
 * string-literal types. Feeding this shape into use-intl's `AppConfig.Messages`
 * (see `packages/react/src/i18n/messages.d.ts`) types every `useTranslations`
 * namespace and `t("key")` call against folio's catalog: a referenced key that
 * en.json does not carry becomes a typecheck error instead of a runtime
 * `MISSING_MESSAGE`. It also lets use-intl enforce ICU interpolation params at
 * the type level.
 *
 * Ported from stella/stella's `packages/scripts/src/i18n-typegen.ts` (same
 * maintainer and license), trimmed to folio's single-file catalog layout.
 *
 * Usage: i18n-typegen <langs-dir> [--check]
 *
 * --check  Verify the on-disk messages.gen.ts matches what would be generated
 *          from en.json. Exits non-zero on drift without writing.
 */
import path from "node:path";

type JsonValue = string | JsonObject;
type JsonObject = {
  [key: string]: JsonValue;
};

const isJsonObject = (value: unknown): value is JsonObject =>
  typeof value === "object" &&
  value !== null &&
  !Array.isArray(value) &&
  Object.values(value).every(
    (entry): entry is JsonValue => typeof entry === "string" || isJsonObject(entry),
  );

const parseMessages = (json: string): JsonObject => {
  const parsed: unknown = JSON.parse(json);
  if (!isJsonObject(parsed)) {
    console.error("Expected en.json to contain only nested objects and strings");
    process.exit(1);
  }

  return parsed;
};

const args = process.argv.slice(2);
const langsDir = args.find((a) => !a.startsWith("--"));
const checkOnly = args.includes("--check");

if (!langsDir) {
  console.error("Usage: i18n-typegen <langs-dir> [--check]");
  process.exit(1);
}

const inputPath = path.resolve(langsDir, "en.json");
const outputPath = path.resolve(langsDir, "messages.gen.ts");

const json = await Bun.file(inputPath).text();
const messages = parseMessages(json);

const indent = (depth: number) => "  ".repeat(depth);

let keyCount = 0;

const toLiteral = (value: JsonValue, depth: number): string => {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return "Record<string, never>";
    }

    const lines = entries.map(([key, val]) => {
      keyCount++;
      return `${indent(depth + 1)}${JSON.stringify(key)}: ${toLiteral(val, depth + 1)};`;
    });
    return `{\n${lines.join("\n")}\n${indent(depth)}}`;
  }

  return "never";
};

const declaration = `// Auto-generated by scripts/i18n-typegen.ts from en.json.
// Do not edit manually; run \`bun run typegen\` to regenerate.

type Messages = ${toLiteral(messages, 0)};

export type { Messages as default };
`;

if (checkOnly) {
  const existing = await Bun.file(outputPath)
    .text()
    .catch(() => "");
  if (existing !== declaration) {
    console.error(`Error: ${outputPath} is out of sync with en.json. Run \`bun run typegen\`.`);
    process.exit(1);
  }
  console.log(`${outputPath} is in sync (${keyCount} keys)`);
} else {
  await Bun.write(outputPath, declaration);
  console.log(`Generated ${outputPath} (${keyCount} keys)`);
}
