/**
 * Generates `packages/core/src/i18n/messages/catalogs.gen.ts` by inlining every
 * `*.json` locale catalog as a typed TS object literal.
 *
 * Core builds with tsdown `unbundle: true`, which mirrors each imported `.json`
 * to a per-locale `dist/i18n/messages/<locale>.js` module; rolldown emits a
 * malformed `export { <locale>_default as default, folio }` for those (the
 * `folio` named binding is never declared), which breaks any downstream bundler
 * that processes core's dist. Inlining the catalogs into one committed `.ts`
 * module keeps raw `.json` out of the build graph, so no per-locale `.js` is
 * emitted. The `.json` files stay: the i18n tooling (typegen, i18n-check) reads
 * the directory directly.
 *
 * Run: `bun scripts/i18n-catalogs-gen.ts`
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

// Locale ordering mirrors FOLIO_LOCALES in messages.ts; `en` first so it is the
// structural source of truth for the generated type.
const LOCALES = [
  "en",
  "de",
  "fr",
  "es",
  "cs",
  "ar",
  "et",
  "he",
  "hi",
  "hu",
  "lt",
  "lv",
  "pl",
  "pt-BR",
  "sk",
  "tr",
  "zh-CN",
] as const;

const messagesDir = path.resolve(import.meta.dir, "../packages/core/src/i18n/messages");
const outputPath = path.join(messagesDir, "catalogs.gen.ts");

const entries = LOCALES.map((locale) => {
  const json = readFileSync(path.join(messagesDir, `${locale}.json`), "utf8");
  const value = JSON.stringify(JSON.parse(json), null, 2);
  // Re-indent the JSON body so the object literal reads cleanly inside CATALOGS.
  const indented = value
    .split("\n")
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join("\n");
  return `  ${JSON.stringify(locale)}: ${indented}`;
}).join(",\n");

const banner = `// Auto-generated by scripts/i18n-catalogs-gen.ts from the sibling *.json locale
// catalogs. Do not edit manually; run \`bun scripts/i18n-catalogs-gen.ts\` to
// regenerate.
//
// The locale catalogs are inlined here (rather than imported as raw \`.json\`) so
// tsdown's \`unbundle: true\` build keeps \`.json\` out of the build graph and emits
// no malformed per-locale \`dist/i18n/messages/<locale>.js\` modules. The \`*.json\`
// files remain the source of truth the i18n tooling reads.`;

const contents = `${banner}\nexport const CATALOGS = {\n${entries},\n} as const;\n`;

writeFileSync(outputPath, contents);
console.log(`Wrote ${path.relative(process.cwd(), outputPath)}`);
